baseurl = "https://eyeson-team.github.io/api/"
languageCode = "en-us"
title = "Eyeson API Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "eyeson GmbH"
	description = "Eyeson API Documentation"
	copyright = "eyeson GmbH"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eyeson-team/api"

	version = "1.0.5"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["eyeson.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "light-blue"

    [params.font]
    	text = "Hubot Sans"
    	code = "Ubuntu Mono"

[social]
	twitter = "eyeson_team"
	github  = "eyeson-team"
	email   = ""


[[menu.main]]
	name   = "Eyeson API"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "API Reference"
	url    = "api-reference/"
	weight = 20

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
